import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import { builtinModules } from "module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Health Connect & Readiness Dashboard for Obsidian
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		{
			name: "local-extractors-resolver",
			setup(build) {
				const localPath = path.resolve("./src/extractors/localExtractors.ts");
				if (fs.existsSync(localPath)) {
					build.onResolve({ filter: /extractors\/activeExtractors$/ }, () => {
						return { path: localPath };
					});
				}
			}
		}
	]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
